### ISSUE TITLE
error_log possible cronable issue

### ISSUE THREAD

**Issue by 737simpilot** [Maikuolan/Cronable#2] opened 2018-02-02 20:05 UTC
I see this in the main directory outside of public_html. I asked my host and he says it could be related to a script or cron. 

[31-Jan-2018 01:00:01 America/Chicago] PHP Warning:  Module 'timezonedb' already loaded in Unknown on line 0
[01-Feb-2018 01:00:01 America/Chicago] PHP Warning:  Module 'timezonedb' already loaded in Unknown on line 0
[02-Feb-2018 01:00:01 America/Chicago] PHP Warning:  Module 'timezonedb' already loaded in Unknown on line 0

Actually, looking at the time, it is related to cronable since that's the time it executes.

**Comment by Maikuolan** [comment] 2018-02-04 10:24
*Issue dealt with via private messaging between @737simpilot and myself. Turned out to be a host problem; Not a bug. Marking as resolved and closing.*

**Closed as completed by Maikuolan** 2018-02-04 10:24 UTC
Labels: Support, Resolved
